import React, { useState, useMemo } from 'react';
import { useJobApplicationImport } from '../../hooks/useJobApplicationImport';
import { useJobStore } from '../../state/useJobStore';
import { useCreateJob } from '../../hooks/useJobs';
import { AutomatorStatusBadge } from './AutomatorStatusBadge';
import { StatusBadgeDropdown } from '../common/StatusBadgeDropdown';
import type { JobItem } from '../../types/job';
import { 
  Mail, 
  ExternalLink, 
  CheckCircle2, 
  Search, 
  RefreshCw, 
  Bot,
  Sparkles,
  FileText,
  Paperclip,
  Check,
  Copy,
  ChevronDown,
  ChevronUp,
  Play,
  Terminal,
  BookOpen,
  Smartphone
} from 'lucide-react';
import { WebAutomatorModal } from './WebAutomatorModal';
import { GmailDraftEditorModal } from './GmailDraftEditorModal';
import { assembleFullOutreachEmail } from '../../services/emailAssembler';

interface JobApplicationPanelProps {
  jobs?: JobItem[];
  isLoading?: boolean;
}

const AUTOMATOR_STEPS = [
  {
    step: '01',
    title: 'Scan Gmail Drafts',
    subtitle: 'Inbox Detection',
    description: 'Inspects your Gmail Drafts for messages with a recipient address and an attached or embedded JD screenshot image.',
    icon: Mail,
    color: '#3b82f6',
    bg: 'rgba(59, 130, 246, 0.12)'
  },
  {
    step: '02',
    title: 'OCR Extraction',
    subtitle: 'Tesseract Vision',
    description: 'Uses Tesseract OCR to extract company name, role title, required tech stack, and key responsibilities from screenshot images.',
    icon: FileText,
    color: '#8b5cf6',
    bg: 'rgba(139, 92, 246, 0.12)'
  },
  {
    step: '03',
    title: 'Claude AI Tailoring',
    subtitle: 'Custom Outreach',
    description: 'Synthesizes extracted requirements with your candidate profile & resume to compose a compelling, personalized cold email.',
    icon: Sparkles,
    color: '#f59e0b',
    bg: 'rgba(245, 158, 11, 0.12)'
  },
  {
    step: '04',
    title: 'Draft & Attachment',
    subtitle: 'Gmail Generation',
    description: 'Generates a new Gmail draft with recipient, subject, body, and your resume PDF attached, ready for your 1-click review.',
    icon: Paperclip,
    color: '#10b981',
    bg: 'rgba(16, 185, 129, 0.12)'
  },
  {
    step: '05',
    title: 'NextApply Auto-Sync',
    subtitle: 'Tracker Integration',
    description: 'Posts webhook payload to NextApply API, logging the job opportunity, recruiter details, and Gmail draft link in the dashboard.',
    icon: CheckCircle2,
    color: '#06b6d4',
    bg: 'rgba(6, 182, 212, 0.12)'
  }
];

export const JobApplicationPanel: React.FC<JobApplicationPanelProps> = ({
  jobs: controlledJobs,
  isLoading: controlledIsLoading,
}) => {
  const { setSelectedJobId, showToast, userProfile, currentUser, filterState } = useJobStore();
  const liveImport = useJobApplicationImport();
  const createJobMutation = useCreateJob();

  const rawJobs = controlledJobs ?? liveImport.automatorJobs;
  const isLoading = controlledIsLoading ?? liveImport.isLoading;
  const isPraveen = currentUser?.id === 'user_praveen' || userProfile?.fullName?.includes('Praveen') || (!currentUser && !userProfile.fullName);
  const userEmail = currentUser?.email || userProfile?.email || '2pkashyap2001@gmail.com';

  // Ensure any legacy jobs for Praveen are accurately tailored to SDE & Full Stack
  const jobs = useMemo(() => {
    return rawJobs.map((job) => {
      if (isPraveen && job.companyName === 'HashiCorp' && (job.targetRole?.includes('DevOps') || job.outreachSubject?.includes('Candidate Introduction'))) {
        return {
          ...job,
          targetRole: 'Senior Full Stack Software Engineer (FSD / React / Go)',
          domain: 'sde' as const,
          hrRecruiterName: 'engineering-hiring@hashicorp.com',
          outreachSubject: 'Senior Full Stack Engineer Application – Praveen Kashyap',
          outreachBodyPreview: 'Hi HashiCorp Team, With 5+ years specializing in Full Stack development, modern React micro-frontends, high-performance Go/C# distributed backends, and cloud-native workflows, I would love to contribute to HashiCorp products...',
          notes: 'Auto-generated by Claude for Praveen Kashyap (SDE & Full Stack).'
        };
      }
      return job;
    });
  }, [rawJobs, isPraveen]);

  const [search, setSearch] = useState('');
  const [statusFilter, setStatusFilter] = useState<'All' | 'Draft Created' | 'Sent' | 'Skipped'>('All');
  const [showSetupGuide, setShowSetupGuide] = useState(false);
  const [isWebModalOpen, setIsWebModalOpen] = useState(false);
  const [copiedCmd, setCopiedCmd] = useState<string | null>(null);
  const [isSeedingDemo, setIsSeedingDemo] = useState(false);
  const [activeEditorJob, setActiveEditorJob] = useState<JobItem | null>(null);

  const filteredJobs = useMemo(() => {
    return jobs.filter((job) => {
      // Domain workspace filter (All Tracks vs SDE & Fullstack vs Cloud & DevOps)
      const matchDomain =
        filterState.activeDomain === 'all' ||
        job.domain === filterState.activeDomain ||
        job.domain === 'dual';

      const matchSearch =
        !search.trim() ||
        job.companyName.toLowerCase().includes(search.toLowerCase()) ||
        job.targetRole.toLowerCase().includes(search.toLowerCase()) ||
        (job.outreachSubject && job.outreachSubject.toLowerCase().includes(search.toLowerCase())) ||
        (job.hrRecruiterName && job.hrRecruiterName.toLowerCase().includes(search.toLowerCase()));

      const matchStatus =
        statusFilter === 'All' || job.automatorStatus === statusFilter;

      return matchDomain && matchSearch && matchStatus;
    });
  }, [jobs, search, statusFilter, filterState.activeDomain]);

  const copyToClipboard = (text: string, id: string) => {
    navigator.clipboard.writeText(text);
    setCopiedCmd(id);
    showToast('Command copied to clipboard');
    setTimeout(() => setCopiedCmd(null), 2000);
  };

  const getGmailAction = (job: JobItem) => {
    const authParam = userEmail ? `authuser=${encodeURIComponent(userEmail)}` : '';

    if (job.automatorStatus === 'Sent') {
      const searchTarget = job.hrRecruiterName || job.companyName;
      return {
        label: 'View in Sent',
        title: `Search sent email in Gmail (${userEmail})`,
        url: `https://mail.google.com/mail/u/?${authParam}#search/${encodeURIComponent(searchTarget)}`,
        icon: Mail
      };
    }

    if (job.gmailDraftId && !job.gmailDraftId.startsWith('draft-') && !job.gmailDraftId.startsWith('web-')) {
      return {
        label: 'Open Draft',
        title: `Open draft in Gmail (${userEmail})`,
        url: `https://mail.google.com/mail/u/?${authParam}#drafts/${job.gmailDraftId}`,
        icon: ExternalLink
      };
    }

    // Direct pre-filled compose in target Gmail account with full multi-paragraph pitch & signature
    const to = encodeURIComponent(job.hrRecruiterName || '');
    const su = encodeURIComponent(job.outreachSubject || '');
    const fullBody = assembleFullOutreachEmail(job, userProfile);
    const body = encodeURIComponent(fullBody);
    return {
      label: 'Open Draft',
      title: `Open publication-ready draft in Gmail (${userEmail})`,
      url: `https://mail.google.com/mail/u/?${authParam}&view=cm&fs=1&to=${to}&su=${su}&body=${body}`,
      icon: ExternalLink
    };
  };

  const handleSeedDemoApplications = async () => {
    setIsSeedingDemo(true);
    try {
      const candidateName = userProfile.fullName || 'Praveen Kashyap';
      const isSde = (userProfile.targetDomain === 'sde') || (!userProfile.targetDomain && userProfile.currentRole?.toLowerCase().includes('sde')) || userProfile.fullName.includes('Praveen');

      const sampleApps: Partial<JobItem>[] = isSde ? [
        {
          companyName: 'Stripe',
          targetRole: 'Senior Full Stack Engineer (.NET / React)',
          domain: 'sde',
          location: 'Remote',
          workMode: 'Remote',
          priority: 'High',
          applicationStatus: 'Applied',
          hrRecruiterName: 'recruiting@stripe.com',
          gmailDraftId: 'draft-stripe-9821',
          automatorStatus: 'Draft Created',
          outreachSubject: `Senior Full Stack Engineer Application – ${candidateName}`,
          outreachBodyPreview: `Hi Team, I noticed your opening for a Senior Full Stack Engineer. With ${userProfile.yoe || '3+ years'} specializing in distributed systems, C# .NET Core, Angular, React, and cloud microservices...`,
          appliedDate: new Date().toISOString().slice(0, 10),
          notes: 'Auto-generated by Claude from screenshot JD. Resume attached.'
        },
        {
          companyName: 'Datadog',
          targetRole: 'Senior Full Stack & Systems Engineer',
          domain: 'sde',
          location: 'San Francisco, CA (Hybrid)',
          workMode: 'Hybrid',
          priority: 'High',
          applicationStatus: 'Interviewing',
          hrRecruiterName: 'talent-infra@datadoghq.com',
          gmailDraftId: 'draft-datadog-4421',
          automatorStatus: 'Sent',
          outreachSubject: `Senior Full Stack Engineer Application – ${candidateName}`,
          outreachBodyPreview: `Hello Datadog Recruiting Team, Having architected high-performance web systems in Angular/React and robust distributed backend APIs with ${userProfile.yoe || '3+ years'} experience...`,
          appliedDate: new Date(Date.now() - 86400000 * 2).toISOString().slice(0, 10),
          notes: 'Sent via Gmail Automator for Praveen Kashyap.'
        },
        {
          companyName: 'Snowflake',
          targetRole: 'Senior Backend Developer / SDE (C# / Go)',
          domain: 'sde',
          location: 'Remote',
          workMode: 'Remote',
          priority: 'High',
          applicationStatus: 'Not Started',
          hrRecruiterName: 'careers@snowflake.com',
          gmailDraftId: 'draft-snowflake-7712',
          automatorStatus: 'Draft Created',
          outreachSubject: `Senior Backend Developer role – ${candidateName}`,
          outreachBodyPreview: `Dear Hiring Team, I am reaching out regarding the Senior Backend Developer position. With ${userProfile.yoe || '3+ years'} building high-throughput microservices in C# .NET and data pipelines...`,
          appliedDate: new Date().toISOString().slice(0, 10),
          notes: 'Draft created in Gmail. Pending final review before sending.'
        },
        {
          companyName: 'HashiCorp',
          targetRole: 'Senior Full Stack Software Engineer (FSD / React / Go)',
          domain: 'sde',
          location: 'Remote',
          workMode: 'Remote',
          priority: 'High',
          applicationStatus: 'Not Started',
          hrRecruiterName: 'engineering-hiring@hashicorp.com',
          gmailDraftId: 'draft-hashi-3390',
          automatorStatus: 'Draft Created',
          outreachSubject: `Senior Full Stack Engineer Application – ${candidateName}`,
          outreachBodyPreview: `Hi HashiCorp Team, With ${userProfile.yoe || '3+ years'} hands-on experience in Full Stack development, modern React and Angular micro-frontends, high-performance Go/C# distributed backends, and cloud-native workflows, I would love to contribute to HashiCorp products...`,
          appliedDate: new Date().toISOString().slice(0, 10),
          notes: 'Auto-generated by Claude for Praveen Kashyap (SDE & Full Stack).'
        }
      ] : [
        {
          companyName: 'AWS / Amazon',
          targetRole: 'Senior Cloud Solutions Architect',
          domain: 'cloud',
          location: 'Remote',
          workMode: 'Remote',
          priority: 'High',
          applicationStatus: 'Applied',
          hrRecruiterName: 'aws-recruiting@amazon.com',
          gmailDraftId: 'draft-aws-1011',
          automatorStatus: 'Draft Created',
          outreachSubject: `Senior Cloud Solutions Architect Application – ${candidateName}`,
          outreachBodyPreview: `Hi Team, I am applying for the Cloud Solutions Architect opening. With ${userProfile.yoe || '3+ years'} architecting resilient AWS multi-region infrastructure...`,
          appliedDate: new Date().toISOString().slice(0, 10),
          notes: 'Generated via Claude Vision automator.'
        },
        {
          companyName: 'Datadog',
          targetRole: 'Cloud Infrastructure & SRE Specialist',
          domain: 'cloud',
          location: 'San Francisco, CA (Hybrid)',
          workMode: 'Hybrid',
          priority: 'High',
          applicationStatus: 'Interviewing',
          hrRecruiterName: 'talent-infra@datadoghq.com',
          gmailDraftId: 'draft-datadog-4421',
          automatorStatus: 'Sent',
          outreachSubject: `Application: Cloud Infrastructure & SRE – ${candidateName}`,
          outreachBodyPreview: `Hello Datadog Recruiting, Having architected multi-region Kubernetes clusters with automated CI/CD and observability pipelines...`,
          appliedDate: new Date(Date.now() - 86400000 * 2).toISOString().slice(0, 10),
          notes: 'Sent via Gmail Automator.'
        },
        {
          companyName: 'HashiCorp',
          targetRole: 'DevOps & Platform Systems Engineer',
          domain: 'cloud',
          location: 'Remote',
          workMode: 'Remote',
          priority: 'Medium',
          applicationStatus: 'Not Started',
          hrRecruiterName: 'devops-hiring@hashicorp.com',
          gmailDraftId: 'draft-hashi-3390',
          automatorStatus: 'Draft Created',
          outreachSubject: `DevOps & Platform Systems Engineer Application – ${candidateName}`,
          outreachBodyPreview: `Hi HashiCorp Team, With extensive hands-on experience in Terraform automation, Kubernetes orchestration, and cloud observability...`,
          appliedDate: new Date().toISOString().slice(0, 10),
          notes: 'OCR extracted from recruiter screenshot. Ready in Gmail drafts.'
        }
      ];

      for (const sample of sampleApps) {
        await createJobMutation.mutateAsync(sample);
      }
      showToast(`Imported ${isSde ? 'SDE & Full Stack' : 'Cloud & DevOps'} applications for ${candidateName}!`);
    } catch (err: any) {
      showToast('Failed to load sample applications');
    } finally {
      setIsSeedingDemo(false);
    }
  };

  if (isLoading) {
    return (
      <div
        data-testid="loading-skeleton"
        style={{
          padding: '32px',
          display: 'flex',
          flexDirection: 'column',
          gap: '16px',
          alignItems: 'center',
          justifyContent: 'center',
          minHeight: '300px',
          color: 'var(--text-muted)',
        }}
      >
        <RefreshCw size={28} className="animate-spin" style={{ color: 'var(--text-accent)' }} />
        <span>Loading auto-imported job applications...</span>
      </div>
    );
  }

  return (
    <div style={{ display: 'flex', flexDirection: 'column', height: '100%', overflowY: 'auto' }}>
      
      {/* Top Banner & Quick Controls */}
      <div
        style={{
          padding: '20px 24px',
          borderBottom: '1px solid var(--border-color)',
          backgroundColor: 'var(--bg-secondary)',
          display: 'flex',
          flexDirection: 'column',
          gap: '16px',
        }}
      >
        <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', flexWrap: 'wrap', gap: '12px' }}>
          <div style={{ display: 'flex', alignItems: 'center', gap: '12px' }}>
            <div
              style={{
                width: '42px',
                height: '42px',
                borderRadius: '10px',
                background: 'linear-gradient(135deg, #3b82f6 0%, #8b5cf6 100%)',
                display: 'flex',
                alignItems: 'center',
                justifyContent: 'center',
                color: '#fff',
                boxShadow: '0 2px 8px rgba(59, 130, 246, 0.3)'
              }}
            >
              <Bot size={22} />
            </div>
            <div>
              <div style={{ display: 'flex', alignItems: 'center', gap: '8px' }}>
                <h2 style={{ fontSize: '1.125rem', fontWeight: 700, color: 'var(--text-primary)', margin: 0 }}>
                  Gmail JD Automator
                </h2>
                <span
                  style={{
                    fontSize: '0.6875rem',
                    fontWeight: 700,
                    padding: '2px 8px',
                    borderRadius: '9999px',
                    backgroundColor: 'rgba(59, 130, 246, 0.15)',
                    color: '#3b82f6',
                  }}
                >
                  AI Vision & Outreach
                </span>
              </div>
              <p style={{ fontSize: '0.8125rem', color: 'var(--text-muted)', margin: '2px 0 0 0' }}>
                Converts Gmail screenshot drafts into tailored outreach emails with Claude & Tesseract OCR.
              </p>
            </div>
          </div>

          {/* Quick Header Actions */}
          <div style={{ display: 'flex', alignItems: 'center', gap: '8px', flexWrap: 'wrap' }}>
            <button
              onClick={() => setIsWebModalOpen(true)}
              style={{
                display: 'inline-flex',
                alignItems: 'center',
                gap: '6px',
                padding: '7px 14px',
                borderRadius: 'var(--radius-sm)',
                background: 'linear-gradient(135deg, #3b82f6 0%, #8b5cf6 100%)',
                border: 'none',
                color: '#fff',
                cursor: 'pointer',
                fontSize: '0.8125rem',
                fontWeight: 600,
                boxShadow: '0 2px 8px rgba(59, 130, 246, 0.3)',
                transition: 'all 150ms ease'
              }}
              className="glow-hover"
            >
              <Smartphone size={15} />
              <span>Run Online Automator</span>
            </button>

            <button
              onClick={() => setShowSetupGuide(!showSetupGuide)}
              style={{
                display: 'inline-flex',
                alignItems: 'center',
                gap: '6px',
                padding: '7px 12px',
                borderRadius: 'var(--radius-sm)',
                backgroundColor: showSetupGuide ? 'var(--bg-active)' : 'var(--bg-tertiary)',
                border: '1px solid var(--border-color)',
                color: showSetupGuide ? 'var(--text-primary)' : 'var(--text-secondary)',
                cursor: 'pointer',
                fontSize: '0.8125rem',
                fontWeight: 600,
                transition: 'all 150ms ease'
              }}
              className="glow-hover"
            >
              <BookOpen size={15} style={{ color: '#8b5cf6' }} />
              <span>How Automator Works & Setup Guide</span>
              {showSetupGuide ? <ChevronUp size={14} /> : <ChevronDown size={14} />}
            </button>

            {jobs.length === 0 && (
              <button
                onClick={handleSeedDemoApplications}
                disabled={isSeedingDemo}
                style={{
                  display: 'inline-flex',
                  alignItems: 'center',
                  gap: '6px',
                  padding: '7px 14px',
                  borderRadius: 'var(--radius-sm)',
                  backgroundColor: 'var(--primary-bg)',
                  border: '1px solid var(--border-focus)',
                  color: 'var(--text-accent)',
                  cursor: 'pointer',
                  fontSize: '0.8125rem',
                  fontWeight: 600,
                  transition: 'all 150ms ease'
                }}
                className="glow-hover"
              >
                <Play size={14} />
                <span>{isSeedingDemo ? 'Loading...' : 'Load Sample Automator Runs'}</span>
              </button>
            )}
          </div>
        </div>

        {/* Quick Metrics Bar when applications exist */}
        {jobs.length > 0 && (
          <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', gap: '12px', flexWrap: 'wrap' }}>
            <div style={{ display: 'flex', alignItems: 'center', gap: '8px', flexWrap: 'wrap' }}>
              <div style={{ padding: '4px 10px', borderRadius: 'var(--radius-sm)', backgroundColor: 'var(--bg-tertiary)', fontSize: '0.75rem', color: 'var(--text-secondary)', display: 'inline-flex', alignItems: 'center' }}>
                <span style={{ width: '7px', height: '7px', borderRadius: '50%', backgroundColor: '#3b82f6', marginRight: '6px', display: 'inline-block' }} />
                Drafts Created: <strong style={{ marginLeft: '4px' }}>{filteredJobs.filter((j) => j.automatorStatus === 'Draft Created').length}</strong>
              </div>
              <div style={{ padding: '4px 10px', borderRadius: 'var(--radius-sm)', backgroundColor: 'var(--bg-tertiary)', fontSize: '0.75rem', color: 'var(--text-secondary)', display: 'inline-flex', alignItems: 'center' }}>
                <span style={{ width: '7px', height: '7px', borderRadius: '50%', backgroundColor: '#10b981', marginRight: '6px', display: 'inline-block' }} />
                Direct Sent: <strong style={{ marginLeft: '4px' }}>{filteredJobs.filter((j) => j.automatorStatus === 'Sent').length}</strong>
              </div>
              <div style={{ padding: '4px 10px', borderRadius: 'var(--radius-sm)', backgroundColor: 'var(--bg-tertiary)', fontSize: '0.75rem', color: 'var(--text-secondary)', display: 'inline-flex', alignItems: 'center' }}>
                <span style={{ width: '7px', height: '7px', borderRadius: '50%', backgroundColor: '#f59e0b', marginRight: '6px', display: 'inline-block' }} />
                Marked Applied: <strong style={{ marginLeft: '4px' }}>{filteredJobs.filter((j) => j.applicationStatus === 'Applied').length}</strong>
              </div>
              <div style={{ padding: '4px 10px', borderRadius: 'var(--radius-sm)', backgroundColor: 'rgba(59, 130, 246, 0.08)', border: '1px solid rgba(59, 130, 246, 0.2)', fontSize: '0.75rem', color: 'var(--text-secondary)', display: 'inline-flex', alignItems: 'center', gap: '6px' }}>
                <Mail size={13} style={{ color: '#3b82f6' }} />
                <span>Account: <strong style={{ color: 'var(--text-primary)' }}>{userEmail}</strong></span>
              </div>
            </div>

            {/* Filter Search */}
            <div style={{ display: 'flex', alignItems: 'center', gap: '8px' }}>
              <div style={{ position: 'relative', width: '220px' }}>
                <Search
                  size={14}
                  style={{
                    position: 'absolute',
                    left: '10px',
                    top: '50%',
                    transform: 'translateY(-50%)',
                    color: 'var(--text-muted)',
                  }}
                />
                <input
                  type="text"
                  placeholder="Filter company or subject..."
                  value={search}
                  onChange={(e) => setSearch(e.target.value)}
                  style={{
                    width: '100%',
                    padding: '5px 10px 5px 28px',
                    fontSize: '0.8125rem',
                    backgroundColor: 'var(--bg-tertiary)',
                    border: '1px solid var(--border-color)',
                    borderRadius: 'var(--radius-sm)',
                    color: 'var(--text-primary)',
                    outline: 'none',
                  }}
                />
              </div>

              <div style={{ display: 'flex', alignItems: 'center', gap: '4px' }}>
                {(['All', 'Draft Created', 'Sent', 'Skipped'] as const).map((st) => (
                  <button
                    key={st}
                    onClick={() => setStatusFilter(st)}
                    style={{
                      padding: '4px 8px',
                      fontSize: '0.75rem',
                      fontWeight: statusFilter === st ? 700 : 500,
                      borderRadius: 'var(--radius-sm)',
                      border: '1px solid',
                      borderColor: statusFilter === st ? 'var(--border-focus)' : 'var(--border-color)',
                      backgroundColor: statusFilter === st ? 'var(--bg-active)' : 'transparent',
                      color: statusFilter === st ? 'var(--text-primary)' : 'var(--text-muted)',
                      cursor: 'pointer',
                    }}
                  >
                    {st}
                  </button>
                ))}
              </div>
            </div>
          </div>
        )}
      </div>

      {/* Expandable How Automator Works / Setup Guide */}
      {(showSetupGuide || jobs.length === 0) && (
        <div
          style={{
            padding: '24px',
            backgroundColor: 'var(--bg-primary)',
            borderBottom: '1px solid var(--border-color)',
            display: 'flex',
            flexDirection: 'column',
            gap: '20px'
          }}
        >
          {/* Section Heading */}
          <div>
            <div style={{ display: 'flex', alignItems: 'center', gap: '8px', marginBottom: '4px' }}>
              <Sparkles size={16} style={{ color: '#f59e0b' }} />
              <h3 style={{ fontSize: '0.9375rem', fontWeight: 700, color: 'var(--text-primary)', margin: 0 }}>
                Automator Pipeline: What It Does Step-by-Step
              </h3>
            </div>
            <p style={{ fontSize: '0.8125rem', color: 'var(--text-muted)', margin: 0 }}>
              The Python automator operates asynchronously in the background. Here is the exact sequence executed for each JD:
            </p>
          </div>

          {/* 5-Step Process Cards Grid */}
          <div style={{
            display: 'grid',
            gridTemplateColumns: 'repeat(auto-fit, minmax(200px, 1fr))',
            gap: '12px'
          }}>
            {AUTOMATOR_STEPS.map((s) => {
              const Icon = s.icon;
              return (
                <div
                  key={s.step}
                  style={{
                    backgroundColor: 'var(--bg-secondary)',
                    border: '1px solid var(--border-color)',
                    borderRadius: 'var(--radius-md)',
                    padding: '14px',
                    display: 'flex',
                    flexDirection: 'column',
                    gap: '8px',
                    position: 'relative'
                  }}
                >
                  <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between' }}>
                    <div style={{
                      width: '32px',
                      height: '32px',
                      borderRadius: '8px',
                      backgroundColor: s.bg,
                      color: s.color,
                      display: 'flex',
                      alignItems: 'center',
                      justifyContent: 'center'
                    }}>
                      <Icon size={16} />
                    </div>
                    <span style={{
                      fontSize: '0.6875rem',
                      fontWeight: 800,
                      color: 'var(--text-muted)',
                      fontFamily: 'monospace'
                    }}>
                      STEP {s.step}
                    </span>
                  </div>

                  <div>
                    <h4 style={{ fontSize: '0.8125rem', fontWeight: 700, color: 'var(--text-primary)', margin: '0 0 2px 0' }}>
                      {s.title}
                    </h4>
                    <span style={{ fontSize: '0.6875rem', color: s.color, fontWeight: 600 }}>
                      {s.subtitle}
                    </span>
                  </div>

                  <p style={{ fontSize: '0.75rem', color: 'var(--text-muted)', lineHeight: 1.4, margin: 0 }}>
                    {s.description}
                  </p>
                </div>
              );
            })}
          </div>

          {/* Quick Setup & Runtime Execution Box */}
          <div style={{
            backgroundColor: 'var(--bg-secondary)',
            border: '1px solid var(--border-color)',
            borderRadius: 'var(--radius-md)',
            padding: '16px 20px',
            display: 'flex',
            flexDirection: 'column',
            gap: '12px'
          }}>
            <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', flexWrap: 'wrap', gap: '8px' }}>
              <div style={{ display: 'flex', alignItems: 'center', gap: '8px' }}>
                <Terminal size={16} style={{ color: 'var(--text-accent)' }} />
                <span style={{ fontSize: '0.8125rem', fontWeight: 700, color: 'var(--text-primary)' }}>
                  How to Run the Automator on Your Machine
                </span>
              </div>
              <span style={{ fontSize: '0.75rem', color: 'var(--text-muted)' }}>
                Sidecar Location: <code style={{ color: 'var(--text-secondary)' }}>automation/gmail-jd-automator/</code>
              </span>
            </div>

            {/* Run Commands Row */}
            <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(280px, 1fr))', gap: '10px' }}>
              {/* Option 1: 1-Click Batch */}
              <div style={{
                padding: '10px 14px',
                backgroundColor: 'var(--bg-tertiary)',
                borderRadius: 'var(--radius-sm)',
                border: '1px solid var(--border-color)',
                display: 'flex',
                alignItems: 'center',
                justifyContent: 'space-between'
              }}>
                <div>
                  <div style={{ fontSize: '0.6875rem', fontWeight: 600, color: 'var(--text-muted)' }}>
                    Windows 1-Click Launcher (Recommended)
                  </div>
                  <code style={{ fontSize: '0.75rem', color: '#10b981', fontWeight: 600 }}>
                    run-automator.bat
                  </code>
                </div>
                <button
                  type="button"
                  onClick={() => copyToClipboard('run-automator.bat', 'bat')}
                  style={{
                    background: 'transparent',
                    border: 'none',
                    color: 'var(--text-muted)',
                    cursor: 'pointer',
                    padding: '4px'
                  }}
                  title="Copy command"
                >
                  {copiedCmd === 'bat' ? <Check size={14} style={{ color: '#10b981' }} /> : <Copy size={14} />}
                </button>
              </div>

              {/* Option 2: Python Command */}
              <div style={{
                padding: '10px 14px',
                backgroundColor: 'var(--bg-tertiary)',
                borderRadius: 'var(--radius-sm)',
                border: '1px solid var(--border-color)',
                display: 'flex',
                alignItems: 'center',
                justifyContent: 'space-between'
              }}>
                <div>
                  <div style={{ fontSize: '0.6875rem', fontWeight: 600, color: 'var(--text-muted)' }}>
                    Direct Python Execution
                  </div>
                  <code style={{ fontSize: '0.75rem', color: '#38bdf8', fontWeight: 600 }}>
                    python automation/gmail-jd-automator/main.py
                  </code>
                </div>
                <button
                  type="button"
                  onClick={() => copyToClipboard('python automation/gmail-jd-automator/main.py', 'py')}
                  style={{
                    background: 'transparent',
                    border: 'none',
                    color: 'var(--text-muted)',
                    cursor: 'pointer',
                    padding: '4px'
                  }}
                  title="Copy command"
                >
                  {copiedCmd === 'py' ? <Check size={14} style={{ color: '#10b981' }} /> : <Copy size={14} />}
                </button>
              </div>
            </div>

            {/* Prerequisites Checklist */}
            <div style={{
              display: 'flex',
              alignItems: 'center',
              gap: '16px',
              flexWrap: 'wrap',
              fontSize: '0.75rem',
              color: 'var(--text-muted)',
              borderTop: '1px solid var(--border-color)',
              paddingTop: '10px'
            }}>
              <span><strong>Prerequisites:</strong></span>
              <span>1. Python 3.9+</span>
              <span>2. Google Cloud OAuth (<code style={{ color: 'var(--text-secondary)' }}>credentials.json</code>)</span>
              <span>3. Anthropic API Key (<code style={{ color: 'var(--text-secondary)' }}>ANTHROPIC_API_KEY</code>)</span>
              <span>4. Tesseract OCR (<code style={{ color: 'var(--text-secondary)' }}>tesseract.exe</code>)</span>
            </div>
          </div>
        </div>
      )}

      {/* Main Table of Auto-Imported Applications */}
      {jobs.length > 0 ? (
        <div style={{ flex: 1, overflowX: 'auto', padding: '16px 24px 32px' }}>
          <table
            data-testid="job-app-panel"
            style={{
              width: '100%',
              borderCollapse: 'separate',
              borderSpacing: '0 6px',
              fontSize: '0.8125rem',
            }}
          >
            <thead>
              <tr style={{ color: 'var(--text-muted)', textAlign: 'left' }}>
                <th style={{ padding: '12px 14px', fontWeight: 600 }}>Company & Recruiter</th>
                <th style={{ padding: '12px 14px', fontWeight: 600 }}>Claude Outreach Subject & Preview</th>
                <th style={{ padding: '12px 14px', fontWeight: 600 }}>Automator Status</th>
                <th style={{ padding: '12px 14px', fontWeight: 600 }}>Tracker Status</th>
                <th style={{ padding: '12px 14px', fontWeight: 600, textAlign: 'right' }}>Actions</th>
              </tr>
            </thead>
            <tbody>
              {filteredJobs.map((job) => {
                const action = getGmailAction(job);

                return (
                  <tr
                    key={job.id}
                    data-testid={`job-row-${job.id}`}
                    onClick={() => setSelectedJobId(job.id)}
                    style={{
                      backgroundColor: 'var(--bg-secondary)',
                      borderRadius: 'var(--radius-sm)',
                      cursor: 'pointer',
                      transition: 'all 120ms ease',
                    }}
                    onMouseEnter={(e) => {
                      e.currentTarget.style.backgroundColor = 'var(--bg-hover)';
                    }}
                    onMouseLeave={(e) => {
                      e.currentTarget.style.backgroundColor = 'var(--bg-secondary)';
                    }}
                  >
                    {/* Company & Recruiter */}
                    <td style={{ padding: '12px 14px', borderTopLeftRadius: 'var(--radius-sm)', borderBottomLeftRadius: 'var(--radius-sm)' }}>
                      <div style={{ fontWeight: 700, color: 'var(--text-primary)', fontSize: '0.875rem' }}>
                        {job.companyName}
                      </div>
                      <div style={{ fontSize: '0.6875rem', color: 'var(--text-muted)', marginTop: '2px' }}>
                        {job.hrRecruiterName ? `To: ${job.hrRecruiterName}` : job.targetRole}
                      </div>
                    </td>

                    {/* Subject Preview */}
                    <td style={{ padding: '12px 14px', maxWidth: '380px' }}>
                      <div
                        style={{
                          color: 'var(--text-primary)',
                          fontWeight: 500,
                          whiteSpace: 'nowrap',
                          overflow: 'hidden',
                          textOverflow: 'ellipsis',
                        }}
                        title={job.outreachSubject}
                      >
                        {job.outreachSubject || '—'}
                      </div>
                      {job.outreachBodyPreview && (
                        <div
                          style={{
                            fontSize: '0.6875rem',
                            color: 'var(--text-muted)',
                            whiteSpace: 'nowrap',
                            overflow: 'hidden',
                            textOverflow: 'ellipsis',
                            marginTop: '2px',
                          }}
                        >
                          {job.outreachBodyPreview}
                        </div>
                      )}
                    </td>

                    {/* Automator Run Status */}
                    <td style={{ padding: '12px 14px' }}>
                      <div data-testid={`status-${job.id}`}>
                        <AutomatorStatusBadge status={job.automatorStatus || 'Draft Created'} />
                      </div>
                    </td>

                    {/* Current Application Status */}
                    <td
                      style={{ padding: '12px 14px' }}
                      onClick={(e) => e.stopPropagation()}
                    >
                      <StatusBadgeDropdown jobId={job.id} currentStatus={job.applicationStatus} size="sm" />
                    </td>

                    {/* Actions */}
                    <td
                      style={{
                        padding: '12px 14px',
                        textAlign: 'right',
                        borderTopRightRadius: 'var(--radius-sm)',
                        borderBottomRightRadius: 'var(--radius-sm)',
                      }}
                      onClick={(e) => e.stopPropagation()}
                    >
                      <div style={{ display: 'inline-flex', alignItems: 'center', gap: '8px' }}>
                        {action && (
                          action.label === 'Open Draft' ? (
                            <button
                              type="button"
                              onClick={(e) => {
                                e.stopPropagation();
                                setActiveEditorJob(job);
                              }}
                              data-testid={`open-draft-${job.id}`}
                              title={`Open draft in Native Dark Gmail Editor (${userEmail})`}
                              style={{
                                display: 'inline-flex',
                                alignItems: 'center',
                                gap: '4px',
                                padding: '4px 10px',
                                fontSize: '0.75rem',
                                fontWeight: 600,
                                borderRadius: 'var(--radius-sm)',
                                backgroundColor: 'rgba(59, 130, 246, 0.12)',
                                color: '#3b82f6',
                                border: '1px solid rgba(59, 130, 246, 0.25)',
                                cursor: 'pointer',
                                transition: 'all 120ms ease',
                              }}
                              className="glow-hover"
                            >
                              <span>{action.label}</span>
                              <action.icon size={12} />
                            </button>
                          ) : (
                            <a
                              href={action.url}
                              target="_blank"
                              rel="noopener noreferrer"
                              data-testid={`open-draft-${job.id}`}
                              title={action.title}
                              style={{
                                display: 'inline-flex',
                                alignItems: 'center',
                                gap: '4px',
                                padding: '4px 10px',
                                fontSize: '0.75rem',
                                fontWeight: 600,
                                borderRadius: 'var(--radius-sm)',
                                backgroundColor: job.automatorStatus === 'Sent' ? 'rgba(16, 185, 129, 0.12)' : 'rgba(59, 130, 246, 0.12)',
                                color: job.automatorStatus === 'Sent' ? '#10b981' : '#3b82f6',
                                textDecoration: 'none',
                                transition: 'all 120ms ease',
                              }}
                              className="glow-hover"
                            >
                              <span>{action.label}</span>
                              <action.icon size={12} />
                            </a>
                          )
                        )}

                        {job.applicationStatus !== 'Applied' && (
                          <button
                            onClick={() => liveImport.markAsApplied(job.id)}
                            style={{
                              display: 'inline-flex',
                              alignItems: 'center',
                              gap: '4px',
                              padding: '4px 10px',
                              fontSize: '0.75rem',
                              fontWeight: 600,
                              borderRadius: 'var(--radius-sm)',
                              backgroundColor: 'rgba(34, 197, 94, 0.12)',
                              color: '#22c55e',
                              border: 'none',
                              cursor: 'pointer',
                              transition: 'all 120ms ease',
                            }}
                            className="glow-hover"
                            title="Mark this application as Applied in tracker"
                          >
                            <CheckCircle2 size={12} />
                            <span>Mark Applied</span>
                          </button>
                        )}
                      </div>
                    </td>
                  </tr>
                );
              })}
            </tbody>
          </table>
        </div>
      ) : null}

      <WebAutomatorModal 
        isOpen={isWebModalOpen} 
        onClose={() => setIsWebModalOpen(false)} 
      />

      <GmailDraftEditorModal
        isOpen={!!activeEditorJob}
        onClose={() => setActiveEditorJob(null)}
        job={jobs.find((j) => j.id === activeEditorJob?.id) || activeEditorJob}
        userProfile={userProfile}
      />
    </div>
  );
};
