// <auto-generated />
using System;
using System.Text.Json;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NextApply.Api.Data;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace NextApply.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260810160100_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("NextApply.Api.Models.Job", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ApplicationLink")
                        .HasColumnType("text")
                        .HasColumnName("application_link");

                    b.Property<string>("ApplicationStatus")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("Not Started")
                        .HasColumnName("application_status");

                    b.Property<DateOnly?>("AppliedDate")
                        .HasColumnType("date")
                        .HasColumnName("applied_date");

                    b.Property<string>("CareerPageLink")
                        .HasColumnType("text")
                        .HasColumnName("career_page_link");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("company_name");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Domain")
                        .HasColumnType("text")
                        .HasColumnName("domain");

                    b.Property<string>("HrRecruiterName")
                        .HasColumnType("text")
                        .HasColumnName("hr_recruiter_name");

                    b.Property<string>("Location")
                        .HasColumnType("text")
                        .HasColumnName("location");

                    b.Property<string>("NextAction")
                        .HasColumnType("text")
                        .HasColumnName("next_action");

                    b.Property<string>("Priority")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("Medium")
                        .HasColumnName("priority");

                    b.Property<string>("ReferralContactName")
                        .HasColumnType("text")
                        .HasColumnName("referral_contact_name");

                    b.Property<bool>("ReferralNeeded")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("referral_needed");

                    b.Property<string>("TargetRole")
                        .HasColumnType("text")
                        .HasColumnName("target_role");

                    b.Property<string>("TechStack")
                        .HasColumnType("text")
                        .HasColumnName("tech_stack");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("WorkMode")
                        .HasColumnType("text")
                        .HasColumnName("work_mode");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationStatus")
                        .HasDatabaseName("idx_jobs_status");

                    b.HasIndex("Domain")
                        .HasDatabaseName("idx_jobs_domain");

                    b.HasIndex("Priority")
                        .HasDatabaseName("idx_jobs_priority");

                    b.ToTable("jobs", (string)null);
                });

            modelBuilder.Entity("NextApply.Api.Models.Note", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<int>("JobId")
                        .HasColumnType("integer")
                        .HasColumnName("job_id");

                    b.Property<string>("NoteType")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("General")
                        .HasColumnName("note_type");

                    b.HasKey("Id");

                    b.HasIndex("JobId");

                    b.ToTable("notes", (string)null);
                });

            modelBuilder.Entity("NextApply.Api.Models.OutreachTemplateUsed", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Channel")
                        .HasColumnType("text")
                        .HasColumnName("channel");

                    b.Property<int>("JobId")
                        .HasColumnType("integer")
                        .HasColumnName("job_id");

                    b.Property<string>("RecipientName")
                        .HasColumnType("text")
                        .HasColumnName("recipient_name");

                    b.Property<DateTime>("SentAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("sent_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("TemplateName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("template_name");

                    b.HasKey("Id");

                    b.HasIndex("JobId");

                    b.ToTable("outreach_templates_used", (string)null);
                });

            modelBuilder.Entity("NextApply.Api.Models.Settings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ActiveTrack")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("Dual Domain")
                        .HasColumnName("active_track");

                    b.Property<JsonElement?>("ContactLinks")
                        .HasColumnType("jsonb")
                        .HasColumnName("contact_links");

                    b.Property<string>("ExperienceSummary")
                        .HasColumnType("text")
                        .HasColumnName("experience_summary");

                    b.Property<string>("FullName")
                        .HasColumnType("text")
                        .HasColumnName("full_name");

                    b.Property<string>("KeyStrengths")
                        .HasColumnType("text")
                        .HasColumnName("key_strengths");

                    b.Property<string>("Theme")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("dark")
                        .HasColumnName("theme");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id");

                    b.ToTable("settings", (string)null);
                });

            modelBuilder.Entity("NextApply.Api.Models.Note", b =>
                {
                    b.HasOne("NextApply.Api.Models.Job", "Job")
                        .WithMany("Notes")
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Job");
                });

            modelBuilder.Entity("NextApply.Api.Models.OutreachTemplateUsed", b =>
                {
                    b.HasOne("NextApply.Api.Models.Job", "Job")
                        .WithMany("OutreachTemplatesUsed")
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Job");
                });

            modelBuilder.Entity("NextApply.Api.Models.Job", b =>
                {
                    b.Navigation("Notes");

                    b.Navigation("OutreachTemplatesUsed");
                });
#pragma warning restore 612, 618
        }
    }
}
